import "../../public/styles/globals.css";
import "../../public/styles/hamburgerMenu.css";
import Head from "next/head";
import type { AppProps } from "next/app";
import Navigation from "../components/Layout/navigation";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";

config.autoAddCss = false;

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Sky Quest</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700&display=swap&family=Unna&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <Navigation />
      <Component {...pageProps} />
    </>
  );
}
